Create database PRACTICAPROFESIONAL 
GO

USE PRACTICAPROFESIONAL
GO

CREATE TABLE USUARIOS(
Id_Usuario INT PRIMARY KEY IDENTITY (1,1),
NombreUsuario NVARCHAR(50),
Email NVARCHAR(50),
Contrasena INT 
);

INSERT USUARIOS VALUES ('nicolas','nicolas_moreno@gmail.com',123);

CREATE TABLE LOCALIDAD(
ID_LOCALIDAD INT PRIMARY KEY IDENTITY (1,1),
DESCRIPCION NVARCHAR(50),
);

INSERT LOCALIDAD VALUES ('RAMOS MEJIA'),('CUIDADELA'),('MORON'),('LAFERRERE'),('VILLA LUZURIAGA'),('ISIDRO CASANOVA'),('RAFAEL CASTILLO'),('LOMAS DEL MIRADOR'),('CABA');
						
CREATE TABLE PROFESOR(
ID_PROFESOR INT PRIMARY KEY IDENTITY (1,1),
NOMBRE NVARCHAR(50),
APELLIDO NVARCHAR(50),
EMAIL NVARCHAR(50),
TELEFONO INT,
ID_LOCALIDAD INT
FOREIGN KEY (ID_LOCALIDAD) REFERENCES LOCALIDAD(ID_LOCALIDAD)
);

INSERT PROFESOR VALUES  ('GONZALO','REYNOSO','G.REYNOSO@INST46.COM',1122334455,1),
						('LUIS','GORRINI','L.GORRINI@INST46.COM',1162738471,3),
						('LUIS','FERNANDEZ','L.FERNANDEZ@INST46.COM',1164726300,5),
						('ANALIA','ARTOLA','A.ARTOLA@INST46.COM',1165278901,9),
						('MARIANO','DOGLOTTI','M.DOGLIOTTI@INST46.COM',1112762877,1),
						('JULIO','BOSSERO','J.BOSSERO@INST46.COM',1187227910,3),
						('DAVID','SANDOVAL','D.SANDOVAL@INST46.COM',1188990262,6);

CREATE TABLE MATERIA(
ID_MATERIA INT PRIMARY KEY IDENTITY (1,1),
DESCRIPCION NVARCHAR(50),
);

INSERT MATERIA VALUES   ('SISTEMAS DE INFORMACION'),
						('EDI 1'),
						('METODOLOGIA DE LA INVESTIGACION'),
						('ANALISIS MATEMATICO'),
						('PROGRAMACION'),
						('BASE DE DATOS'),
						('PROGRAMACION ORIENTADA A OBJETOS'),
						('GESTION DE BASE DE DATOS'),
						('PRACTICA PROFESIONAL');

CREATE TABLE DICTA_MATERIA(
ID  INT PRIMARY KEY IDENTITY (1,1),
ID_PROFESOR INT,
ID_MATERIA INT,
PRECIO FLOAT
FOREIGN KEY (ID_PROFESOR) REFERENCES PROFESOR(ID_PROFESOR),
FOREIGN KEY (ID_MATERIA) REFERENCES MATERIA(ID_MATERIA)
);

INSERT DICTA_MATERIA VALUES (1,2,9500),
							(1,9,15000),
							(2,1,10500),
							(3,4,12000),
							(4,3,10000),
							(5,7,13500),
							(6,6,7500),
							(6,8,9500),
							(5,6,9500);







